-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	user_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	date_of_birth date NOT NULL,
	email varchar(320) NOT NULL,
	first_name varchar(100) NOT NULL,
	is_admin bool NOT NULL,
	last_name varchar(100) NOT NULL,
	password_hash varchar(255) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool DEFAULT true NOT NULL,
	created_at timestamptz(6) NOT NULL,
	e_pin varchar(255) NULL,
	"role" varchar(20) DEFAULT 'USER'::character varying NOT NULL,
	updated_at timestamptz(6) NOT NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (user_id),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


-- public.accounts definition

-- Drop table

-- DROP TABLE public.accounts;

CREATE TABLE public.accounts (
	account_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	balance numeric(38, 2) NOT NULL,
	currency varchar(3) NOT NULL,
	iban varchar(34) NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT accounts_pkey PRIMARY KEY (account_id),
	CONSTRAINT uknubpiuxhnr0f0tl3tx3y9i80u UNIQUE (iban),
	CONSTRAINT fknjuop33mo69pd79ctplkck40n FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);


-- public.bank_accounts definition

-- Drop table

-- DROP TABLE public.bank_accounts;

CREATE TABLE public.bank_accounts (
	iban varchar(18) NOT NULL,
	balance numeric(18, 2) NOT NULL,
	currency varchar(3) NOT NULL,
	account_name varchar(80) NULL,
	"name" varchar(80) NOT NULL,
	status varchar(10) DEFAULT 'ACTIVE'::character varying NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT bank_accounts_pkey PRIMARY KEY (iban),
	CONSTRAINT bank_accounts_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'BLOCKED'::character varying])::text[]))),
	CONSTRAINT fkahrj5m84hfc167gpma9vcwe0j FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);


-- public.transactions definition

-- Drop table

-- DROP TABLE public.transactions;

CREATE TABLE public.transactions (
	tran_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric(18, 2) NOT NULL,
	credited_amount numeric(18, 2) NOT NULL,
	destination_currency varchar(3) NOT NULL,
	exchange_rate_used numeric(18, 6) NOT NULL,
	reason varchar(255) NOT NULL,
	source_currency varchar(3) NOT NULL,
	status varchar(255) NOT NULL,
	"time_stamp" timestamptz(6) NOT NULL,
	destination_account_iban varchar(18) NOT NULL,
	source_account_iban varchar(18) NOT NULL,
	CONSTRAINT transactions_pkey PRIMARY KEY (tran_id),
	CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
	CONSTRAINT fklblafl8besiug88fuauxkgic5 FOREIGN KEY (source_account_iban) REFERENCES public.bank_accounts(iban),
	CONSTRAINT fknqveqtb76xmlt35q9cvu3yh3b FOREIGN KEY (destination_account_iban) REFERENCES public.bank_accounts(iban)
);


-- public.transaction_logs definition

-- Drop table

-- DROP TABLE public.transaction_logs;

CREATE TABLE public.transaction_logs (
	log_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	log_entry_text text NOT NULL,
	"time_stamp" timestamptz(6) NOT NULL,
	tran_id int8 NOT NULL,
	CONSTRAINT transaction_logs_pkey PRIMARY KEY (log_id),
	CONSTRAINT fk3ovrnk7pj01axdnir4ofs8yyj FOREIGN KEY (tran_id) REFERENCES public.transactions(tran_id)
);